version: "3.9"
services:
  localstack:
    image: localstack/localstack:3
    environment:
      - SERVICES=sqs,sns
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "./.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
